// function namedAction(action: any) {
//   eval(`export const ${action} = action`)
//   eval(`export type ${action} = action`)
// }
// Task

  // search
export const TA_COLLAPSE_ONCLICK = 'TA_COLLAPSE_ONCLICK';
export const TA_NODE_ONCLICK = 'TA_NODE_ONCLICK';
export const TA_CLEAR_SELECTED_SEARCH = 'TA_CLEAR_SELECTED_SEARCH';
export const TA_CLEAR_ALL_SEARCH = 'TA_CLEAR_ALL_SEARCH';
export const TA_FAST_SEARCH_ONCLICK = 'TA_FAST_SEARCH_ONCLICK';
export const TA_ADVANCED_SEARCH_ONCONFIRM = 'TA_ADVANCED_SEARCH_ONCONFIRM';
export const TA_ADVANCED_SEARCH_ONCANCEL = 'TA_ADVANCED_SEARCH_ONCANCEL';

  // taskDetail // TODO v0.2
export const TA_TASK_ONCLICK = 'TA_TASK_ONCLICK';
export const TA_CLOSE_MODAL_ONCLICK = 'TA_CLOSE_MODAL_ONCLICK';
export const TA_MODAL_ONCONFIRM = 'TA_MODAL_ONCONFIRM';
export const TA_MODAL_ONNOTKEEP = 'TA_MODAL_ONNOTKEEP';
export const TA_MODAL_ONKEEP = 'TA_MODAL_ONKEEP';

  // task
export const TP_INIT = 'TP_INIT';
export const TA_TAB_ONCLICK = 'TA_TAB_ONCLICK';
export const TA_ADVANCED_SEARCH_ONCLICK = 'TA_ADVANCED_SEARCH_ONCLICK';
export const TA_TASK_SORT_TIME_FORWARD = 'TA_TASK_SORT_TIME_FORWARD';
export const TA_TASK_SORT_TIME_BACKWARD = 'TA_TASK_SORT_TIME_BACKWARD';
export const TA_CHANGE_PAGE = 'TA_CHANGE_PAGE';
export const TA_ADD_TASK_ONCLICK = 'TA_ADD_TASK_ONCLICK';
export const TA_DELETE_TASK_ONCLICK = 'TA_DELETE_TASK_ONCLICK';
